#!/bin/bash
# sync-frontend-env.sh - フロントエンド環境変数同期コマンド

# ライブラリの読み込み
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/input.sh"
source "${SCRIPT_DIR}/lib/network.sh"
source "${SCRIPT_DIR}/lib/env_manager.sh"

# 環境変数ファイルのパスを設定
initialize_env_manager "$SCRIPT_DIR"

# フロントエンドディレクトリのパス
FRONTEND_DIR="$(cd "${SCRIPT_DIR}/../../frontend" && pwd)"
FRONTEND_ENV="${FRONTEND_DIR}/.env"

# 同期前の確認
pre_sync_check() {
    log_section "同期前確認"

    # フロントエンドディレクトリの確認
    if [[ ! -d "$FRONTEND_DIR" ]]; then
        log_error "フロントエンドディレクトリが見つかりません: ${FRONTEND_DIR}"
        return 1
    fi

    # フロントエンド .env の確認（なければ自動生成）
    if [[ ! -f "$FRONTEND_ENV" ]]; then
        log_warning "フロントエンド .env が見つかりません: ${FRONTEND_ENV}"
        log_info "現行フォーマットに合わせてフロントエンド .env を自動生成します。"
        {
            echo "# Frontend environment (generated by sync-frontend-env)"
            echo "# Generated at: $(date '+%Y-%m-%d %H:%M:%S')"
            echo ""
            echo "# =========================================="
            echo "# Sui Contract Configuration"
            echo "# =========================================="
            echo "NEXT_PUBLIC_PACKAGE_ID="
            echo "NEXT_PUBLIC_PASSPORT_REGISTRY_ID="
            echo "NEXT_PUBLIC_ADMIN_CAP_ID="
            echo "NEXT_PUBLIC_UPGRADE_CAP_ID="
            echo ""
        } > "$FRONTEND_ENV" || {
            log_error "フロントエンド .env の作成に失敗しました。"
            return 1
        }
        log_success "フロントエンド .env を作成しました。"
    fi

    # 契約環境変数ファイルの確認
    local contract_env=$(get_env_file_path "$SELECTED_NETWORK")
    if [[ ! -f "$contract_env" ]]; then
        log_error "契約環境変数ファイルが見つかりません: ${contract_env}"
        log_info "先にデプロイを実行してください。"
        return 1
    fi

    # 現在の設定を表示
    echo "📋 同期情報"
    echo "────────────────────────────────────────"
    echo "  ネットワーク: ${SELECTED_NETWORK}"
    echo "  契約環境変数: ${contract_env}"
    echo "  フロントエンド: ${FRONTEND_ENV}"
    echo "────────────────────────────────────────"
    echo ""

    return 0
}

# Python3の存在確認
check_python3() {
    if ! command -v python3 &> /dev/null; then
        log_error "python3 が見つかりません。"
        log_info "python3 をインストールしてください。"
        return 1
    fi
    return 0
}

# フロントエンド環境変数を更新（frontend/.env の「Sui Contract Configuration」セクションだけを同期）
update_frontend_env() {
    local source_env=$(get_env_file_path "$SELECTED_NETWORK")
    local target_env="$FRONTEND_ENV"

    log_section "フロントエンド環境変数の更新"

    log_info "📝 環境変数を同期しています..."
    log_info "ソース: ${source_env}"
    log_info "ターゲット: ${target_env}"

    # Python3で環境変数を更新
    python3 - "$source_env" "$target_env" <<'PY'
import pathlib
import sys

CONTRACT_KEYS = [
    "PACKAGE_ID",
    "PASSPORT_REGISTRY_ID",
    "ADMIN_CAP_ID",
    "UPGRADE_CAP_ID",
]

def parse_env(path):
    data = {}
    for line in pathlib.Path(path).read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        if '=' not in stripped:
            continue
        key, value = stripped.split('=', 1)
        data[key.strip()] = value.strip()
    return data

src = parse_env(sys.argv[1])
dst_path = pathlib.Path(sys.argv[2])
dst_lines = dst_path.read_text().splitlines()

section_header = "# Sui Contract Configuration"
separator = "# =========================================="

def find_section(lines):
    header_idx = next((i for i, v in enumerate(lines) if v.strip() == section_header), None)
    if header_idx is None:
        return None, None

    start = header_idx + 1
    while start < len(lines) and (lines[start].strip() == "" or lines[start].lstrip().startswith('#')):
        start += 1

    end = start
    while end < len(lines) and not lines[end].startswith(separator):
        end += 1
    return start, end

start, end = find_section(dst_lines)

if start is None:
    # セクションが見つからない場合は末尾に追加
    dst_lines.extend([
        separator,
        section_header,
        separator,
    ])
    start = len(dst_lines)
    end = start

# 既存値を記録（欠損時のフォールバック用）
existing = {}
for line in dst_lines[start:end]:
    if '=' in line and not line.lstrip().startswith('#'):
        k, v = line.split('=', 1)
        existing[k.strip()] = v.strip()

new_section = []
changes = []

for key in CONTRACT_KEYS:
    target_key = f"NEXT_PUBLIC_{key}"
    if key in src:
        value = src[key]
    elif target_key in existing:
        value = existing[target_key]
    else:
        value = ""

    new_line = f"{target_key}={value}"
    old_line = existing.get(target_key)

    new_section.append(new_line)

    # 変更検知（値が存在しない場合も追加扱い）
    if old_line is None:
        changes.append((target_key, value, "追加"))
    elif old_line != value:
        changes.append((target_key, value, "更新"))

# セクションを書き換え、契約セクション直後に空行を入れる
dst_lines[start:end] = new_section + [""]

dst_path.write_text("\n".join(dst_lines) + "\n")

if changes:
    print("✅ フロントエンド .env を更新しました:")
    for key, value, action in changes:
        display_value = value if len(value) <= 60 else f"{value[:60]}..."
        print(f"  [{action}] {key}={display_value}")
else:
    print("ℹ️  Sui Contract Configuration セクションに更新はありませんでした。")

sys.exit(0)
PY

    local exit_code=$?

    if [[ $exit_code -eq 0 ]]; then
        log_success "フロントエンド環境変数の同期が完了しました。"
        return 0
    else
        log_error "フロントエンド環境変数の同期に失敗しました。"
        return 1
    fi
}

# 同期結果の表示
show_sync_result() {
    log_section "同期結果"

    echo "📄 フロントエンド .env の Sui Contract Configuration セクション:"
    echo "────────────────────────────────────────"

    awk '
        $0=="# Sui Contract Configuration" {in_block=1; seen_sep=0; print; next}
        in_block && /^# ==========================================/ {
            if (seen_sep) {print; exit}
            seen_sep=1
            print
            next
        }
        in_block {print}
    ' "$FRONTEND_ENV" || echo "（セクションが見つかりません）"

    echo "────────────────────────────────────────"
    echo ""
    echo "ファイル: ${FRONTEND_ENV}"
}

# メイン処理
main() {
    # Python3の確認
    if ! check_python3; then
        return 1
    fi

    # 同期前確認
    if ! pre_sync_check; then
        return 1
    fi

    # 確認プロンプト
    if ! prompt_yes_no "フロントエンド .env を同期しますか？" "y"; then
        log_info "同期をキャンセルしました。"
        return 1
    fi

    # フロントエンド環境変数を更新
    if ! update_frontend_env; then
        return 1
    fi

    # 同期結果を表示
    show_sync_result

    return 0
}

# メイン処理を実行
main
exit $?
