#!/bin/bash
# sync-frontend-env.sh - フロントエンド環境変数同期コマンド

# ライブラリの読み込み
source "${SCRIPT_DIR}/lib/logging.sh"
source "${SCRIPT_DIR}/lib/input.sh"
source "${SCRIPT_DIR}/lib/network.sh"
source "${SCRIPT_DIR}/lib/env_manager.sh"

# 環境変数ファイルのパスを設定
initialize_env_manager "$SCRIPT_DIR"

# フロントエンドディレクトリのパス
FRONTEND_DIR="$(cd "${SCRIPT_DIR}/../../frontend" && pwd)"
FRONTEND_ENV="${FRONTEND_DIR}/.env"

# 同期前の確認
pre_sync_check() {
    log_section "同期前確認"

    # フロントエンドディレクトリの確認
    if [[ ! -d "$FRONTEND_DIR" ]]; then
        log_error "フロントエンドディレクトリが見つかりません: ${FRONTEND_DIR}"
        return 1
    fi

    # フロントエンド .env の確認（なければ自動生成）
    if [[ ! -f "$FRONTEND_ENV" ]]; then
        log_warning "フロントエンド .env が見つかりません: ${FRONTEND_ENV}"
        log_info "フロントエンド .env を自動生成します。"
        {
            echo "# Frontend environment"
            echo "# Generated by sync-frontend-env on $(date '+%Y-%m-%d %H:%M:%S')"
            echo ""
            echo "# Sui Contract Configuration"
        } > "$FRONTEND_ENV" || {
            log_error "フロントエンド .env の作成に失敗しました。"
            return 1
        }
        log_success "フロントエンド .env を作成しました。"
    fi

    # 契約環境変数ファイルの確認
    local contract_env=$(get_env_file_path "$SELECTED_NETWORK")
    if [[ ! -f "$contract_env" ]]; then
        log_error "契約環境変数ファイルが見つかりません: ${contract_env}"
        log_info "先にデプロイを実行してください。"
        return 1
    fi

    # 現在の設定を表示
    echo "📋 同期情報"
    echo "────────────────────────────────────────"
    echo "  ネットワーク: ${SELECTED_NETWORK}"
    echo "  契約環境変数: ${contract_env}"
    echo "  フロントエンド: ${FRONTEND_ENV}"
    echo "────────────────────────────────────────"
    echo ""

    return 0
}

# Python3の存在確認
check_python3() {
    if ! command -v python3 &> /dev/null; then
        log_error "python3 が見つかりません。"
        log_info "python3 をインストールしてください。"
        return 1
    fi
    return 0
}

# フロントエンド環境変数を更新（contracts/.env.<network> の全キーを NEXT_PUBLIC_ プレフィクス付きでコピー）
update_frontend_env() {
    local source_env=$(get_env_file_path "$SELECTED_NETWORK")
    local target_env="$FRONTEND_ENV"

    log_section "フロントエンド環境変数の更新"

    log_info "📝 環境変数を同期しています..."
    log_info "ソース: ${source_env}"
    log_info "ターゲット: ${target_env}"

    # Python3で環境変数を更新
    python3 - "$source_env" "$target_env" <<'PY'
import pathlib
import re
import sys

def parse_env(path):
    data = {}
    for line in pathlib.Path(path).read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue
        if '=' not in stripped:
            continue
        key, value = stripped.split('=', 1)
        data[key.strip()] = value.strip()
    return data

src = parse_env(sys.argv[1])
dst_path = pathlib.Path(sys.argv[2])
dst_lines = dst_path.read_text().splitlines()

# 既存キーの位置を記録
line_idx = {}
for idx, line in enumerate(dst_lines):
    if '=' in line and not line.strip().startswith('#'):
        key = line.split('=', 1)[0].strip()
        line_idx[key] = idx

changes = []

for key, value in src.items():
    target_key = key if key.startswith("NEXT_PUBLIC_") else f"NEXT_PUBLIC_{key}"
    new_line = f"{target_key}={value}"
    if target_key in line_idx:
        idx = line_idx[target_key]
        if dst_lines[idx] != new_line:
            dst_lines[idx] = new_line
            changes.append((target_key, value, "更新"))
    else:
        dst_lines.append(new_line)
        changes.append((target_key, value, "追加"))

# ターゲットファイルを更新
dst_path.write_text("\n".join(dst_lines) + "\n")

if changes:
    print("✅ フロントエンド .env を更新しました:")
    for key, value, action in changes:
        display_value = value if len(value) <= 60 else f"{value[:60]}..."
        print(f"  [{action}] {key}={display_value}")
else:
    print("ℹ️  更新する環境変数がありませんでした。")

sys.exit(0)
PY

    local exit_code=$?

    if [[ $exit_code -eq 0 ]]; then
        log_success "フロントエンド環境変数の同期が完了しました。"
        return 0
    else
        log_error "フロントエンド環境変数の同期に失敗しました。"
        return 1
    fi
}

# 同期結果の表示
show_sync_result() {
    log_section "同期結果"

    echo "📄 フロントエンド .env の内容:"
    echo "────────────────────────────────────────"

    # Sui関連の環境変数のみを表示
    grep "^NEXT_PUBLIC_SUI" "$FRONTEND_ENV" || echo "（Sui関連の環境変数が見つかりません）"

    echo "────────────────────────────────────────"
    echo ""
    echo "ファイル: ${FRONTEND_ENV}"
}

# メイン処理
main() {
    # Python3の確認
    if ! check_python3; then
        return 1
    fi

    # 同期前確認
    if ! pre_sync_check; then
        return 1
    fi

    # 確認プロンプト
    if ! prompt_yes_no "フロントエンド .env を同期しますか？" "y"; then
        log_info "同期をキャンセルしました。"
        return 1
    fi

    # フロントエンド環境変数を更新
    if ! update_frontend_env; then
        return 1
    fi

    # 同期結果を表示
    show_sync_result

    return 0
}

# メイン処理を実行
main
exit $?
